### ISSUE TITLE
Line Fitting

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#247] opened 2018-07-17 20:50 UTC
From @keflavich: "should use the `astropy.modeling` machinery (including choices for the user of model and fitter) but wrap it in a useful/easy way"

**Comment by eteq** [comment] 2018-07-17 20:53
To expand more: this is a *very* broad topic - this "meta issue" is to try to wrap a lot of idas together in one.

Key guideline: there is *not* "one true way" to do line fitting.  Rather `specutils` should provide a toolbox of pieces that make it straightforward to do standard things, but also doesn't get in the way of more advanced/experimental methods.

A general guide (in progress at the top of this writing) for how this might work is here: https://github.com/spacetelescope/dat_pyinthesky/blob/master/pyinthesky_specutils_fitting.ipynb
with a start at implementation in #210.

None of this is set in stone, and all is open for discussion here... But we are trying to get some initial implementation done in a unified way consistent with `Spectrum1D` so that there's something to build from.

**Comment by SaOgaz** [comment] 2018-07-23 17:42
related or duplicate of #195

**Comment by PatrickOgle** [comment] 2020-02-10 16:20
Functionality is available in specutils.  Leave open for further discussion.

**Comment by nmearl** [comment] 2020-05-06 20:11
We currently have documentation that covers the use case of arbitrary models and line fitting. Closing this as a new issue should be open in the case where work needs to be done on adding a dedicated notebook.

**Closed by nmearl** 2020-05-06 20:11 UTC
Labels: discussion, feature
