### ISSUE TITLE
JWST s3d fits loader fails to load files from Box

### ISSUE THREAD

**Issue by PatrickOgle** [astropy/specutils#801] opened 2021-04-01 13:24 UTC
BoxPath = "https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/IFU_optimal_extraction/"
filename = BoxPath + "NRS00001-faintQSO-F100LP-G140H-01_1_491_SE_2020-08-25T12h15m00_s3d.fits"
fname=filename
sp1d = Spectrum1D.read(fname, format='JWST s3d')

Gives this error:
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
<ipython-input-22-9c3abdc05ced> in <module>
      3 #fname="https://public.boxcloud.com/d/1/b1!Enbr6kiRddAVxW24pLZ0Q_HER-2FVridpkzQ4EbuH4HeGc2KYvvlpk7efZZDRVOO2w2INWPa5Pfw5RCt_yeHahtmiLCkCnhIRolAHOQfdEkFMmk9hV1U62jHe83rmhE3iGZwZpJwMYSHCh4riv1F3r_IWvkydypQN4nNA2ZuRB-J7ihXfFO9Roz-T85n2uD3a0nDb4z4lGJu2ZKGjNbFJ98E6BwCzdYwBCO7vu-RgdUauPfgCoe0iFtDqoR3MSUc4myYauhJbByxSy1N60q2LCQ3LnlIDr4RzzuqT4PhB2_8i3vTl-740xBC5fA5Xw68HRDI-Tf6BuzEkDUT9NAEf6fRPPVJAQmLkf8odo1TE34ogIQ_KG9__lG2kIYsmNqBfSRUL0Ib689wd_AFrklE_C541EQqAb25QDFHk9UJ38tj3eqCiEpca66ShkO6KQiVOQqAAx2iuW4RaPEbFxN2ky_Xp3rSYeruXdz795a8-_PiYtMcQvOBv7Pb3QLhRKmOv8cMz0uVkady1kypHdy7y59bMoAld6nI7sZOTyig2OzVzZ6-i2Bm9mx1KneSR6S4m5xxZNY6QOBk7ChykUcTXwY3qqCaLcSwtYOOS98sUKGxHrnLaXh9q7U321SdChU30E_0huL32BruWCRIm-E_lRMZbsQxOv3pblP2E9ugvrGB5WMN_EobHGwycVY-cXrZ6f3cxAjO6rmkYnN4WnwWYzWlr9FBLrDMNNT110CN-T4RfQNBLuetGMJ0_5so5HzcoL2IwAW9rOb8S_2UvJre0ziDnGAYqCV4Sq7HzPn5snbGWnZl6-_yMZDvFFlTIQpA0X0D6-Nyn6zc0SZ-xbQpuAiUfosxHzw5c6je-HegcjX-o3x1lYoR_JtcGLRRbLM3W44EmTToVKtjC57yVAXzLvhiGEaQE6nJtHeP203jk-_728hiGP_v-4wx142yamJyNBHmKbRoF_bPIpgSpZpQYafAOKWdtzoKBe2c6w-I93Mx-ldmBdk6QYWzpcPzXzDXWOBcqz1kp-82mqtiY0x4Js56DrH6cQ9F8UPNLtzqv4gv_MA02XtG3hrvyCPWQj_6bdoBiG0wybeeWyC-EgfGh-ICSQ9Hp-h3tXmbEX8cOIlRV9gOGFDR_1TC4RysohRTq1sPdLI6ZJ9hsGxqBcG4Hn_6zmVRiNdtbM2Qp9vc1WE_Vua99sZLAZNp5Q-5iIEQvzCW9t5WnfJJZCDrOD8THsteylnfbFu7T-Gr4avZsg-PBsXJLW27zLM1MRcEOO3B4-6e5RcG3KGYWTbB5T1Ru2yrJZen_SRR0HMrpxtrYhK5rNe--kWLSduAtwLET7-i8rpRGz8oWTpblI5C4qnEP6IV__P3wreYeiOkJPP8ugD6FfoTXVZo7TyvlRmCcnyHuNBSxBrbOxVHijQOiP-PpYhalWXrYR8FkVdipD2TsEPef5uBzIY6fL1mRFP1hHIN70U3zaTvcE8vEdJT_Q_nVQwH29Q./download"
      4 fname=filename
----> 5 sp1d = Spectrum1D.read(fname, format='JWST s3d')
      6 #w_untrimmed = spec1d_untrimmed.spectral_axis
      7 #print(sp1d_untrimmed.uncertainty)

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/astropy/nddata/mixins/ndio.py in __call__(self, *args, **kwargs)
     56 
     57     def __call__(self, *args, **kwargs):
---> 58         return registry.read(self._cls, *args, **kwargs)
     59 
     60 

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/astropy/io/registry.py in read(cls, format, cache, *args, **kwargs)
    518 
    519         reader = get_reader(format, cls)
--> 520         data = reader(*args, **kwargs)
    521 
    522         if not isinstance(data, cls):

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/specutils/io/default_loaders/jwst_reader.py in jwst_s3d_single_loader(filename, **kwargs)
    340         The spectrum contained in the file.
    341     """
--> 342     spectrum_list = _jwst_s3d_loader(filename, **kwargs)
    343     if len(spectrum_list) == 1:
    344         return spectrum_list[0]

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/specutils/io/default_loaders/jwst_reader.py in _jwst_s3d_loader(filename, **kwargs)
    367 
    368     # Get a list of GWCS objects from the slits
--> 369     with asdf.open(filename) as af:
    370         wcslist = [af.tree["meta"]["wcs"]]
    371 

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/asdf/asdf.py in open_asdf(fd, uri, mode, validate_checksums, extensions, do_not_fill_defaults, ignore_version_mismatch, ignore_unrecognized_tag, _force_raw_types, copy_arrays, lazy_load, custom_schema, strict_extension_check, ignore_missing_extensions, validate_on_read, _compat)
   1478                    custom_schema=custom_schema, _readonly=readonly)
   1479 
-> 1480     return AsdfFile._open_impl(instance,
   1481         fd, uri=uri, mode=mode,
   1482         validate_checksums=validate_checksums,

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/asdf/asdf.py in _open_impl(cls, self, fd, uri, mode, validate_checksums, do_not_fill_defaults, _get_yaml_content, _force_raw_types, strict_extension_check, ignore_missing_extensions, validate_on_read)
    711                    validate_on_read=True):
    712         """Attempt to open file-like object as either AsdfFile or AsdfInFits"""
--> 713         if not is_asdf_file(fd):
    714             try:
    715                 # TODO: this feels a bit circular, try to clean up. Also

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/asdf/asdf.py in is_asdf_file(fd)
   1510     else:
   1511         try:
-> 1512             fd = generic_io.get_file(fd, mode='r', uri=None)
   1513             if not isinstance(fd, io.IOBase):
   1514                 to_close = True

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/asdf/generic_io.py in get_file(init, mode, uri, close)
   1189                 raise ValueError(
   1190                     "HTTP connections can not be opened for writing")
-> 1191             return _make_http_connection(init, mode, uri=uri)
   1192         elif parsed.scheme in _local_file_schemes:
   1193             if mode == 'rw':

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/asdf/generic_io.py in _make_http_connection(init, mode, uri)
   1064     parsed = urlparse.urlparse(init)
   1065     connection = http.client.HTTPConnection(parsed.netloc)
-> 1066     connection.connect()
   1067 
   1068     block_size = io.DEFAULT_BUFFER_SIZE

~/miniconda3/envs/jdaviz1.1/lib/python3.9/http/client.py in connect(self)
    919     def connect(self):
    920         """Connect to the host and port specified in __init__."""
--> 921         self.sock = self._create_connection(
    922             (self.host,self.port), self.timeout, self.source_address)
    923         self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

~/miniconda3/envs/jdaviz1.1/lib/python3.9/socket.py in create_connection(address, timeout, source_address)
    841     if err is not None:
    842         try:
--> 843             raise err
    844         finally:
    845             # Break explicitly a reference cycle

~/miniconda3/envs/jdaviz1.1/lib/python3.9/socket.py in create_connection(address, timeout, source_address)
    829             if source_address:
    830                 sock.bind(source_address)
--> 831             sock.connect(sa)
    832             # Break explicitly a reference cycle
    833             err = None

ConnectionRefusedError: [Errno 61] Connection refused

**Comment by PatrickOgle** [comment] 2021-04-01 13:26
@eteq thinks this might be an issue with how the loader is trying to resolve the URL. @jdavies-st , do you think you can take a look?

**Comment by jdavies-st** [comment] 2021-04-01 15:21
Well, I can't even get this URL to work using `curl`:

```
$ curl https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/IFU_optimal_extraction/NRS00001-faintQSO-F100LP-G140H-01_1_491_SE_2020-08-25T12h15m00_s3d.fits -o test.fits
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
$ ls -l test.fits
-rw-rw-r--  1 jdavies  wheel  0 Apr  1 11:19 test.fits
```

**Comment by jdavies-st** [comment] 2021-04-01 17:05
But it does load without problems using `requests`.

```
In [1]: import asdf

In [2]: import requests

In [3]: from io import BytesIO

In [4]: r = requests.get("https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/IFU_optimal_extraction/NRS00001-faintQSO-F100LP-G140H-01_1_491_SE_2020-08-25T12h15m00_s3d.fits")

In [5]: af = asdf.open(BytesIO(r.content))

In [6]: af.tree["meta"]["wcs"]
Out[6]: 
<WCS(output_frame=world, input_frame=None, forward_transform=Model: CompoundModel
Inputs: ('x0', 'x1', 'x')
Outputs: ('alpha_C', 'delta_C', 'y')
Model set size: 1
Expression: ([0] & [1] | [2] | [3] & [4] | [5] | [6]) & ([7] | [8] | [9])
Components: 
    [0]: <Shift(offset=-16., name='crpix1')>

    [1]: <Shift(offset=-19., name='crpix2')>

    [2]: <AffineTransformation2D(matrix=[[-0.80983022, -0.58666431], [-0.58666431,  0.80983022]], translation=[0., 0.], name='pc_matrix')>

    [3]: <Scale(factor=0.00002778, name='cdelt1')>

    [4]: <Scale(factor=0.00002778, name='cdelt2')>

    [5]: <Pix2Sky_Gnomonic(name='TAN')>

    [6]: <RotateNative2Celestial(lon=156.17789289, lat=-45.68697659, lon_pole=180., name='crval')>

    [7]: <Shift(offset=-0.)>

    [8]: <Scale(factor=0.000235)>

    [9]: <Shift(offset=0.96652146)>
Parameters:
    offset_0 offset_1               matrix_2 [2,2]              translation_2 [2] ... lon_pole_6 offset_7        factor_8             offset_9     
    -------- -------- ----------------------------------------- ----------------- ... ---------- -------- ---------------------- ------------------
       -16.0    -19.0 -0.8098302221786426 .. 0.8098302221786426        0.0 .. 0.0 ...      180.0     -0.0 0.00023499999952036887 0.9665214562483713)>
```

**Comment by jdavies-st** [comment] 2021-04-01 17:10
@eslavich, this looks like something in `asdf` internals that are preventing this?

If downloaded via `wget`:

```
$ wget https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/IFU_optimal_extraction/NRS00001-faintQSO-F100LP-G140H-01_1_491_SE_2020-08-25T12h15m00_s3d.fits
--2021-04-01 13:08:06--  https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/IFU_optimal_extraction/NRS00001-faintQSO-F100LP-G140H-01_1_491_SE_2020-08-25T12h15m00_s3d.fits
Resolving data.science.stsci.edu... 34.231.161.234, 54.172.193.70, 34.203.172.116
Connecting to data.science.stsci.edu|34.231.161.234|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://stsci.box.com/shared/static/lrwxyticdqfwn2j9jdp9qcuhhgqbe6gg.fits [following]
--2021-04-01 13:08:07--  https://stsci.box.com/shared/static/lrwxyticdqfwn2j9jdp9qcuhhgqbe6gg.fits
Resolving stsci.box.com... 107.152.29.197
Connecting to stsci.box.com|107.152.29.197|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/lrwxyticdqfwn2j9jdp9qcuhhgqbe6gg.fits [following]
--2021-04-01 13:08:07--  https://stsci.box.com/public/static/lrwxyticdqfwn2j9jdp9qcuhhgqbe6gg.fits
Reusing existing connection to stsci.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://stsci.app.box.com/public/static/lrwxyticdqfwn2j9jdp9qcuhhgqbe6gg.fits [following]
--2021-04-01 13:08:07--  https://stsci.app.box.com/public/static/lrwxyticdqfwn2j9jdp9qcuhhgqbe6gg.fits
Resolving stsci.app.box.com... 107.152.29.201
Connecting to stsci.app.box.com|107.152.29.201|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!FOng2g6w8yWqcIDoTVsdmuWSElyLLDkxRqf_7wyMiGF6xaWGZcUJuGvwd3yZ425tSt1v-vn1duH3VDL2XBqQ0GknDuxRX44luTNIR50gDAWGsgGPpqQhFBts02_BnuVz7CajdAfkaNWPkxaLA5ag4Ev1bGYyvsX9pXZYZOxjYt4sggRxMRWPtgkXQ443ei0ZCqxb5VI1OrJejH5UuRmbOJCBd1x1ILiPPrCuWS33omhH-mJnEx-IngRdUGrehEXrKvnpSrFbcH-SxXJZRlTUvB6RJBM4BRKl1yQghTYUx7ok4EnxCp2uzfKxm1opTghwmEKtKuiK8q1dXIaYWwzNft6AR4oAtNNlndlamY2QoEOSoiFZXhxa0kNzDJTl3VLyKwhcS8RW0dBv-PgYd9pGSASJ5TrlGp8M_IY3z_7_wCXju4sUrj8vQwNKx-AhFj9S9ENIRdSvZJ9ENvDMS6850OxKBEIRmzzMQGPKTrWN8qx9fXh7d5WniiQ9IPj8mGP_nSw_AJgY-OGaKbQ1pygJEo3z1Ta6QAMh1IBI7ONqaJ8XKg6mzg4NRbgwh11Qo02X0AKJnMxZ1m1_kOaUx_KsC49YR3--I6uR-zXArJIcRb1ttA31CNU5c0cUcT9wJKGoob7H1SNfsZcdPDYBaEfPeaRGVGSurx5A3Zqrf-PeiHoZ2Tr3tZ0QmhrbXav9krbGEpbzmSmj0GkesruN0zqhyIJ4gtn0ShQI8vBl1P58xZq2nbPLf_38WEy9EMXshU9qgTCphZ31o_oixVrrGawR80l90ZLae25Cwpm3gN6z71bwEv5wYHPGjM9bPUK9rkqIasUnzlXc0Q_VtU9xoxyh8h4-pOv5EFOlBAlfXDyPD7cZxHz6ndnOLkgiEXLwHXN3ZdkRHYNo0RcWKylbMx0vOA0Vm-HAtW0Yv8lmE9MjZVd_GfbQyrC42uzDVPVoenlTGXm12Kwp0DzRYDQ7pEwNbTqxF_4zZD0xF-05G2Htm7Fd6FVERohS0BdGMRafwNyQVIg5KvS6B7s6_t9TRyXZAxKxxrB18VaKFyUVtliDL8gq2OinHGW7-rNj9Y7TXhv4g9hnlqa7poxT35oGyD1Un-nTkfMooIDKWa9JTaaD14aWZMek4d6_ptD6ROdjbQC00FLS1JUVoAsShmf2Sw6QSEoKDMj1pIwatR3w7KhwqlW7m8x7vsqvaV8FdvhVV_qflAuPunDz6NpsRMwII1pLvxQaX36eOf25nmGo4GodZI5on5JaHz4Wqq2rdL2eCwQvHH-kgdSNM6MtYv01Boyl81kN2ggjhw062wveMn370G4GZko5_DshKAqF8W67LsVXpMSlyDUz1rXVcpKXFRnPhnnvjRQedOnseDCpci434fELcGBvdKi90aD-f8zlr4mikbP916R9UqBps0Vclhl-LfQvCrASj2KfZJf9QZobg3exMr61WgKDyNzeeQKo50ftV-fLo7o7QJrGh3_t1x8sZiVuAGy1TM7A/download [following]
--2021-04-01 13:08:08--  https://public.boxcloud.com/d/1/b1!FOng2g6w8yWqcIDoTVsdmuWSElyLLDkxRqf_7wyMiGF6xaWGZcUJuGvwd3yZ425tSt1v-vn1duH3VDL2XBqQ0GknDuxRX44luTNIR50gDAWGsgGPpqQhFBts02_BnuVz7CajdAfkaNWPkxaLA5ag4Ev1bGYyvsX9pXZYZOxjYt4sggRxMRWPtgkXQ443ei0ZCqxb5VI1OrJejH5UuRmbOJCBd1x1ILiPPrCuWS33omhH-mJnEx-IngRdUGrehEXrKvnpSrFbcH-SxXJZRlTUvB6RJBM4BRKl1yQghTYUx7ok4EnxCp2uzfKxm1opTghwmEKtKuiK8q1dXIaYWwzNft6AR4oAtNNlndlamY2QoEOSoiFZXhxa0kNzDJTl3VLyKwhcS8RW0dBv-PgYd9pGSASJ5TrlGp8M_IY3z_7_wCXju4sUrj8vQwNKx-AhFj9S9ENIRdSvZJ9ENvDMS6850OxKBEIRmzzMQGPKTrWN8qx9fXh7d5WniiQ9IPj8mGP_nSw_AJgY-OGaKbQ1pygJEo3z1Ta6QAMh1IBI7ONqaJ8XKg6mzg4NRbgwh11Qo02X0AKJnMxZ1m1_kOaUx_KsC49YR3--I6uR-zXArJIcRb1ttA31CNU5c0cUcT9wJKGoob7H1SNfsZcdPDYBaEfPeaRGVGSurx5A3Zqrf-PeiHoZ2Tr3tZ0QmhrbXav9krbGEpbzmSmj0GkesruN0zqhyIJ4gtn0ShQI8vBl1P58xZq2nbPLf_38WEy9EMXshU9qgTCphZ31o_oixVrrGawR80l90ZLae25Cwpm3gN6z71bwEv5wYHPGjM9bPUK9rkqIasUnzlXc0Q_VtU9xoxyh8h4-pOv5EFOlBAlfXDyPD7cZxHz6ndnOLkgiEXLwHXN3ZdkRHYNo0RcWKylbMx0vOA0Vm-HAtW0Yv8lmE9MjZVd_GfbQyrC42uzDVPVoenlTGXm12Kwp0DzRYDQ7pEwNbTqxF_4zZD0xF-05G2Htm7Fd6FVERohS0BdGMRafwNyQVIg5KvS6B7s6_t9TRyXZAxKxxrB18VaKFyUVtliDL8gq2OinHGW7-rNj9Y7TXhv4g9hnlqa7poxT35oGyD1Un-nTkfMooIDKWa9JTaaD14aWZMek4d6_ptD6ROdjbQC00FLS1JUVoAsShmf2Sw6QSEoKDMj1pIwatR3w7KhwqlW7m8x7vsqvaV8FdvhVV_qflAuPunDz6NpsRMwII1pLvxQaX36eOf25nmGo4GodZI5on5JaHz4Wqq2rdL2eCwQvHH-kgdSNM6MtYv01Boyl81kN2ggjhw062wveMn370G4GZko5_DshKAqF8W67LsVXpMSlyDUz1rXVcpKXFRnPhnnvjRQedOnseDCpci434fELcGBvdKi90aD-f8zlr4mikbP916R9UqBps0Vclhl-LfQvCrASj2KfZJf9QZobg3exMr61WgKDyNzeeQKo50ftV-fLo7o7QJrGh3_t1x8sZiVuAGy1TM7A/download
Resolving public.boxcloud.com... 107.152.29.200
Connecting to public.boxcloud.com|107.152.29.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42459840 (40M) [application/octet-stream]
Saving to: 'NRS00001-faintQSO-F100LP-G140H-01_1_491_SE_2020-08-25T12h15m00_s3d.fits'

NRS00001-faintQSO-F100LP-G140H-01_1_ 100%[===================================================================>]  40.49M  3.80MB/s    in 12s     

2021-04-01 13:08:21 (3.51 MB/s) - 'NRS00001-faintQSO-F100LP-G140H-01_1_491_SE_2020-08-25T12h15m00_s3d.fits' saved [42459840/42459840]

```

So clearly there's some URL forwarding happening and `asdf` is not happy about it.

**Comment by eslavich** [comment] 2021-04-01 18:05
ASDF appears to not support https!  Nor does it follow redirects.  I'll file an issue over there.

**Comment by jdavies-st** [comment] 2021-04-12 18:04
This has now been fixed in `asdf` master branch.  The eventual `asdf 2.7.4` release will contain this fix too.

**Comment by eslavich** [comment] 2021-05-03 14:33
asdf 2.7.4 was released on Friday and I confirmed that I am able to call `asdf.open` on the box link in this issue description.

**Comment by nmearl** [comment] 2021-05-03 15:39
Thanks for the confirmation, glad to see this is fixed.

**Closed by nmearl** 2021-05-03 15:39 UTC
Labels: bug, data objects
