### ISSUE TITLE
error in ndcube manually constructing Spectrum1D

### ISSUE THREAD

**Issue by havok2063** [astropy/specutils#815] opened 2021-04-27 18:58 UTC
I'm getting an error when trying to manually construct a Spectrum1D object, inside `ndcube`, `AttributeError: 'SpectralGWCS' object has no attribute 'naxis'`.  Using `specutils=1.2.dev125+gfd7b4aa0`.

To reproduce:
```
import numpy as np
lamb = np.ones(100) * u.AA 
flux = np.ones(100) * 10**-17 * u.Unit('erg cm-2 s-1 AA-1') 
spec = Spectrum1D(spectral_axis=lamb, flux=flux) 
```

Traceback
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-473748a7279e> in <module>
      2 lamb = np.ones(100) * u.AA
      3 flux = np.ones(100) * 10**-17 * u.Unit('erg cm-2 s-1 AA-1')
----> 4 spec = Spectrum1D(spectral_axis=lamb, flux=flux)

~/Work/git/havok2063/specutils/specutils/spectra/spectrum1d.py in __init__(self, flux, spectral_axis, wcs, velocity_convention, rest_value, redshift, radial_velocity, bin_specification, **kwargs)
    254             wcs = gwcs_from_array(np.arange(size) * u.Unit(""))
    255 
--> 256         super().__init__(
    257             data=flux.value if isinstance(flux, u.Quantity) else flux,
    258             wcs=wcs, **kwargs

~/anaconda3/envs/havokve/lib/python3.8/site-packages/ndcube/ndcube.py in __init__(self, data, wcs, uncertainty, mask, meta, unit, extra_coords, copy, missing_axes, **kwargs)
    187             missing_axes = kwargs.get("missing_axis", None)
    188             if missing_axes is None:
--> 189                 missing_axes = [False] * wcs.naxis
    190             else:
    191                 warnings.warn(

AttributeError: 'SpectralGWCS' object has no attribute 'naxis'
```

**Comment by pllim** [comment] 2021-04-27 20:37
At a glance, it looks like `ndcube` doesn't understand GWCS.

**Comment by havok2063** [comment] 2021-04-28 14:46
Additional note, this error also shows up when I attempt to load a JWST x1d file via the `Specviz.load_data` route.  
```
spec = SpecViz()
spec.load_data(filename)
spec.app
```

**Comment by havok2063** [comment] 2021-05-03 16:34
This may be fixed now using `specutils=1.3.dev43+g44f20a6f.d20210503` and `ndcube=2.0.0b3.dev74+g947799e`.  The above code works under these versions.

**Comment by rosteen** [comment] 2021-05-03 17:25
I just confirmed that your code works with both the version of `ndcube` currently pinned in the `specutils` requirements and with their most recent commit on master. Seems like you either had an old version of `ndcube` or managed to grab their dev version at a point where they'd broken it...either way, do you think we can close this?

**Comment by havok2063** [comment] 2021-05-03 20:43
Ok, great.  As long as you can confirm it, then yeah I'm ok closing it.  It seems like it was a temporary issue.

**Closed** 2021-05-05 03:42 UTC
Labels: bug
