### ISSUE TITLE
Test error with Python 3.11

### ISSUE THREAD

**Issue by olebole** [astropy/specutils#993] opened 2022-11-27 14:23 UTC
When building the package with Python 3.11.0, I get the following error:
```
___________________________________________ ERROR collecting specutils/__init__.py ___________________________________________
/usr/lib/python3/dist-packages/pytest_doctestplus/plugin.py:264: in collect
    finder.find(module)
/usr/lib/python3/dist-packages/pytest_doctestplus/plugin.py:674: in find
    tests = doctest.DocTestFinder.find(self, obj, name, module, globs, extraglobs)
/usr/lib/python3.11/doctest.py:940: in find
    self._find(tests, obj, name, module, source_lines, globs, {})
/usr/lib/python3.11/doctest.py:1012: in _find
    self._from_module(module, val)):
/usr/lib/python3.11/doctest.py:974: in _from_module
    raise ValueError(f"{object} must be a class or function")
E   ValueError: <method-wrapper '__init__' of module object at 0x7f10df14d170> must be a class or function
```
This does not happen with Python 3.10.

The object that is causing the ValueError is `<method-wrapper '__init__' of module object at 0x7f6f7845d170>`, while with Python 3.10 it is `<module 'specutils' from '…/specutils/specutils/__init__.py'>`.

I am not sure whether this is a problem of specutils or of pytest-doctestplus; however the unit tests of pytest-doctestplus pass with Python 3.11, so I open the issue here. Feel free to move it if reasonable.

Package versions:

Numpy: 1.21.5
Scipy: 1.8.1
gwcs: 0.18.2
Asdf: 2.13.0

**Comment by pllim** [comment] 2022-11-28 21:51
The usage of this is from astropy-helper days and should be removed. Though not sure if that is the cause or not.

https://github.com/astropy/specutils/blob/f28fe2dfa902ab2e3acdc74e315899b366bc9812/specutils/__init__.py#L13

**Comment by rosteen** [comment] 2023-01-04 14:51
Thanks for the heads up! I'll close this then.

**Closed by rosteen** 2023-01-04 14:51 UTC
