### ISSUE TITLE
Spec1D read is slow compared to astropy.io fits.open

### ISSUE THREAD

**Issue by PatrickOgle** [astropy/specutils#688] opened 2020-06-03 15:41 UTC
I tried two methods to read in a JWST NIRSpec data cube.  While astropy.io fits.open followed by Spectrum1D() takes 0.06 seconds, Spectrum1D.read takes an unbearably long 19.6 seconds.  Why so slow?

**Comment by nmearl** [comment] 2020-06-03 15:47
I would assume because you're actually creating specutils objects, parsing fits data, creating quantities, instantiating `Spectrum1D` and/or `SpectrumCollection` objects.

Of course, ~20 seconds is quite awhile. It could be that the loader isn't particularly efficient. May want to ask @jdavies-st if there are any heinous data parsing occurring in the loader that can speak for the large wait time.

**Comment by jdavies-st** [comment] 2020-06-03 16:41
I suspect it is because the arrays are actually loaded into memory.  `astropy.io.fits.open()` is basically not doing anything when you call it.  It uses memmap and lazy load to not actually load any of the data arrays into memory.  When you actually have to do that, it will take a bit longer.

Specutils also has some overhead in that its identifier runs if you don't give the `format=` option on `read()`, and that takes time, as it has to open the file at least one further time.  Specifying a format should cut down load time.

20 seconds does seem like a long time.  Hmm.

**Comment by dhomeier** [comment] 2020-06-12 16:53
@PatrickOgle you wrote "followed by Spectrum1D()" – so something like
```
hdu = fits.open('datacube.fits')
spec = Spectrum1D.read(hdu[1])
```
only took 0.06 seconds?

**Comment by pllim** [comment] 2021-09-27 21:52
I still see this. Very annoying.

```
Filename: allcube_ch1-2-3-4-shortlongmedium-_s3d.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     244   ()      
  1  SCI           1 ImageHDU        68   (89, 73, 9099)   float32   
  2  ERR           1 ImageHDU        12   (89, 73, 9099)   float32   
  3  DQ            1 ImageHDU        12   (89, 73, 9099)   int32 (rescales to uint32)   
  4  WMAP          1 ImageHDU        10   (89, 73, 9099)   float32   
  5  WCS-TABLE     1 BinTableHDU     14   1R x 1C   [9099E]   
  6  HDRTAB        1 BinTableHDU    788   24R x 389C   [23A, 24A, D, 48A, 10A, D, D, 5A, 7A, 13A, 4A, D, D, D, D, D, 4A, 10A, D, D, D, D, D, D, 10A, 15A, D, D, 26A, 11A, 5A, 3A, 3A, 2A, 1A, 2A, 5A, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 5A, 4A, 11A, D, 2A, D, D, D, D, 6A, D, D, D, 4A, D, D, D, D, D, D, 4A, D, D, D, D, D, D, D, D, D, D, D, 7A, D, D, D, D, D, D, D, D, D, 4A, D, D, D, K, D, D, K, K, D, D, D, K, D, D, K, D, D, D, D, D, D, D, D, D, K, L, D, D, D, D, D, D, D, D, D, D, 4A, K, K, K, K, K, K, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 6A, 14A, 3A, D, D, 3A, 3A, D, 31A, 3A, 37A, D, D, 3A, 31A, 3A, 3A, 3A, 3A, 3A, 33A, 31A, 3A, 3A, 3A, 30A, D, 36A, 31A, 3A, 3A, D, D, 33A, D, 36A, D, 34A, D, D, 3A, 31A, 37A, 34A, D, D, D, D, D, D, D, D, 42A, D, D, D, D, 8A, D, D, D, D, D, 8A, 8A, D, D, D, D, 8A, 8A, 8A, 7A, 7A, D, D, 8A, 8A, D, 8A, 8A, D, D, D, D, D, D, 8A, 8A, D, D, 7A, 8A, 8A, D, D, 8A, D, D, D, D, D, D, D, D, D, D, 6A, D, D, D, D, 4A, D, D, D, K, K, K, K, D, D, D, 1A, 1A, 1A, 1A, 1A, 1A, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 115A, D, D, K, D, D, D, K, D, D, D, D]   
  7  ASDF          1 BinTableHDU     11   1R x 1C   [140718B]   
```

```python
from specutils import Spectrum1D

fn = 'allcube_ch1-2-3-4-shortlongmedium-_s3d.fits'  # 900 MB
sp = Spectrum1D.read(fn, format='JWST s3d') 
```
```
CPU times: user 25.2 s, sys: 10.7 s, total: 35.8 s
Wall time: 44.5 s
```

**Comment by dhomeier** [comment] 2021-09-27 22:53
OK, I can confirm that it's not the size of the data as such, which only takes some tenths of a second to read from an NVMe disk, but almost the entire time is spent in constructing the wavelength solution
https://github.com/astropy/specutils/blob/8e5da5e5f1230096f131b9b9a1661bfcf0e93079/specutils/io/default_loaders/jwst_reader.py#L587
– don't know if that's just the complexity of the WCS, or a performance issue with GWCS...

**Comment by pllim** [comment] 2021-09-27 22:56
Hmm! Looks like @jdavies-st added that back in #595 .

**Comment by astrofrog** [comment] 2021-09-28 09:33
At a glance I think the issue is that the reader is trying to *evaluate* the WCS in all pixels of the array. There are more efficient ways to do this when not all axes are correlated though, I can try post some more info later.

**Comment by jdavies-st** [comment] 2021-09-28 16:39
Evaluating the WCS should be instantaneous.  These are not complex.  But given that the spatial and spectral components are orthogonal, then we don't really need to evaluate the whole grid of x,y,z points, just a single vector (slice) down the z axis.  Again, since these functions are evaluated with numpy arrays, it should not be a huge difference, though it's possible that because it is using the `Tabular1D` model in the wavelenth array, it's trying to interpolate the whole grid independently, i.e. repeating the simple 1D interpolation 89x73 times.

**Comment by jdavies-st** [comment] 2021-09-28 16:44
Note that a single vector down the z axis is being used anyway

https://github.com/astropy/specutils/blob/8e5da5e5f1230096f131b9b9a1661bfcf0e93079/specutils/io/default_loaders/jwst_reader.py#L590

May as well just evaluate

```python
wcs(*grid[:, 0, 0])
```

instead, which might be much quicker.  Or better yet, don't evaluate, and just read the `Tabular1D` table and assign it.

That said, if the evaluation of the WCS takes this long, it would be good to look at how the JWST pipeline is constructing this `gwcs.WCS` object.

**Comment by jdavies-st** [comment] 2021-09-28 18:09
For this particular dataset, it is much quicker.

```
In [34]: %timeit model.meta.wcs(*grid)
20.4 s ± 655 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [35]: %timeit model.meta.wcs(*grid[:,0,0])
774 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

I'll file a PR to fix it here and will have to look into a way to improve the gwcs transform in the `jwst` package.

**Comment by jdavies-st** [comment] 2021-09-28 18:29
It seems `Tabular1D` is doing a separate 1D interpolation for each of the 73x89 spatial elements in the 3D cube.  Which is generally correct, if each spatial element has different wavelength arrays.  But since the spatial and spectral axes are orthogonal by definition here, every single one of these 1D interpolations is the same for every spatial element, so it's pretty inefficient.  I'll file an issue over in `jwst` and see if we can construct the WCS more efficiently.  Meanwhile, there's an easy workaround for `specutils`.

**Comment by pllim** [comment] 2021-09-28 20:13
Definitely much better with #874 !

**Closed** 2021-10-01 15:00 UTC
Labels: bug, performance
