### ISSUE TITLE
Replacement for IRAF specshift

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#175] opened 2018-04-27 20:01 UTC
http://iraf.net/irafhelp.php?val=specshift&help=Help+Page

*"At the moment, I am using the task `iraf.specshift()` to shift spectra and slightly correct the wavelength calibration with narrow lines. I want to read and save the changed spectrum. Theoretically, it is not difficult to code it myself, but I run the script with 'normal' and 1D spectra at the same time and I am afraid to manipulate directly the pixel values and to save the result in a corrupt format, especially for the 1D spectra. If you know any astro module in Python with this implemented IRAF task..."*

Subset of #165 (but not explicitly mentioned there).

**Comment by eteq** [comment] 2019-10-10 13:42
Note that this is a duplicate of #413 in the sense that  solving #413 will provide a way to do this.  So this can be closed once that's done (although see #523...)

**Comment by rosteen** [comment] 2020-04-24 16:29
It sounds like both this and #413 were solved via #422, can they be closed?

**Closed** 2020-04-24 21:44 UTC
Labels: feature
