### ISSUE TITLE
Expand documentation on writing out Spectrum1D objects

### ISSUE THREAD

**Issue by nmearl** [astropy/specutils#908] opened 2021-12-13 20:58 UTC
The documentation is currently quite reader-heavy in terms of interacting with spectrum data files. This is a proposal to expand the docs to include more information and examples of writing spectrum files out. The intention is that users would get a useful introduction to the writing functionality in tandem with the reading functionality (i.e. add some information around [here](https://specutils.readthedocs.io/en/stable/spectrum1d.html#reading-from-a-file)), expanding as necessary.

Knowing that the results of spectrum manipulation may be saved out and passed around to colleagues, having test and docs that cover typical formats (fits, asdf, etc.) and ensuring they round-trip properly is needed.

**Comment by kelle** [comment] 2021-12-15 02:37
From #529 , more info also needs to provided for handling uncertainties:  "Three uncertainty types are supported: variance (VarianceUncertainty), standard deviation (StdDevUncertainty) and inverse variance (InverseVariance)."

**Comment by pllim** [comment] 2023-02-13 23:01
Duplicate of #905

**Closed by pllim** 2023-02-13 23:01 UTC
