### ISSUE TITLE
Center wavelength position measure

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#240] opened 2018-07-11 19:33 UTC
An estimate of the wavelength position of the center of an emission or absorption feature. splot has some algorithms so a decision will have to be made on which algorithms to implement. 

This might be overtaken by some work in fitting work as one planned feature there is line finding and this appears quite related.

**Comment by eteq** [comment] 2018-07-17 20:31
I think this is essentially a duplicate of #236 now that I look at it?  That is, to get the centroid of an absorption feature, you can just invert the spectrum (assuming it's continuum subtracted, as it needs to be anyway). Anything that actually involved line-fitting should be dealt with separately in the line-fitting process.

**Closed** 2018-09-05 18:07 UTC
Labels: analysis
